name = "InspectDR"
uuid = "d0351b0e-4b05-5898-87b3-e2a8edfddd1d"
version = "0.3.6"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Graphics = "a2bd30eb-e257-5431-a919-1863eab51364"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
NumericIO = "6c575b1c-77cb-5640-a5dc-a54116c90507"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]

[compat]
Graphics = "≥ 0.1.0"
Colors = "≥ 0.9.5"
NumericIO = "≥ 0.3.1"
Cairo = "≥ 0.2.2"
Gtk = "≥ 0.17.0"
julia = "1"
